---
title: Chen Idan.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: דיוקנה של המתמטיקאית כאשת לטאה
description: בלוג על מתמטיקה
avatar: https://avatars0.githubusercontent.com/u/20994544?s=60&v=4
footer-links:
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: barryclark/jekyll-now
  instagram: 
  linkedin: 
  pinterest: 
  rss: 
  twitter: jekyllrb
  stackoverflow: 
  youtube: 
  googleplus: 
disqus: 
google_analytics: 
url: 
baseurl: ''
permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: :expanded
gems:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
theme: jekyll-theme-leap-day
